### ISSUE TITLE
incorrect layering of styles causes poor performance in PC area, particularly while using hotkeys

### ISSUE THREAD

**Issue by ssjshields** [ssjshields/archetype#43] opened 2023-05-07 16:05 UTC
fix WIP, priority issue
this is also causing issue #42

**Comment by realmadrid1809** [comment] 2023-05-07 19:05
Issue was caused by repositioning of displayed pokemon lvl, which made the hitbox for the slot smaller. Fixed by removing border and utilizing font offset instead

**Closed by realmadrid1809** 2023-05-07 19:05 UTC
Labels: bug
